Classes decaration getter
kysect/Fluda pull request #134
Opened 2022-09-26 08:14 UTC by Walter-Rabbit

Closed #128

2022-09-26 08:20 UTC, Walter-Rabbit commented on Source/Kysect.Fluda.CodeGeneration/CodeFirst/CodeParser/ClassesDeclarationGetter.cs
> +        }
В данной реализации, если в файле несколько классов, то это исключение и если наоборот ни один класс не объявлен, то это исключение. 

Если возможно, что в одном файле могут быть несколько моделек в одном файле, то могу сделать так, чтобы просто все классы из файла закидывались в общий список классов.

2022-09-26 08:21 UTC, Walter-Rabbit commented on Source/Kysect.Fluda.Samples/Program.cs
>      private static void Main()
Эх, надо бы начать тестировать код на тестах, а не в мейне. Эх эх эх

2022-09-26 08:49 UTC, FrediKats commented on Source/Kysect.Fluda.Samples/Program.cs
>      private static void Main()
Надо!

2022-09-26 08:52 UTC, Walter-Rabbit commented on Source/Kysect.Fluda.Samples/Program.cs
>      private static void Main()
Сегодня напишу

2022-09-26 08:55 UTC, FrediKats requested changes

2022-09-26 08:55 UTC, FrediKats commented on Source/Kysect.Fluda.CodeGeneration/CodeFirst/CodeParser/ClassesDeclarationGetter.cs
> +            .Select(GetClassDeclaration)
Я бы предложил сделать сначала Select из пути в контент, а в GetClassDeclaration принимать уже код из файла. Тогда метод будет имуть на одну ответственность меньше.

2022-09-26 08:55 UTC, FrediKats commented on Source/Kysect.Fluda.CodeGeneration/CodeFirst/CodeParser/ClassesDeclarationGetter.cs
> +        }
Предлагаю сразу заложить сценарий, что может быть несколько или 0 классов.

- Несколько классов - набросали однотипные классы
- 0 классов - енам, который лежит рядом с той же директории

Можем просто возвращать отсюда коллекцию классов. А для описанных выше случаев предлагаю добавить тут логирование. Будем писать, что в каком-то файле не было классов, чтобы можно было задетектить.

Возможно, в проекте с логированием сейчас не очень, возможно его вообще нет. Если так, то можно завести ишую и протянуть серилог, а тут оставить TODO

2022-09-26 17:52 UTC, Walter-Rabbit commented
Ой, не заметил правки. Щас Отмена повторного ревью.

2022-09-26 18:30 UTC, Walter-Rabbit commented on Source/Kysect.Fluda.CodeGeneration/CodeFirst/CodeParser/ClassesDeclarationGetter.cs
> +            .Select(GetClassDeclaration)
Я хочу в логах возвращать название файла, в котором не были найдены классы. Если я передам в метод с парсингом только текст из файла, то не смогу в логах записать название файла (если не добавлять какие-то флаги).

2022-09-27 03:58 UTC, FrediKats requested changes

2022-09-27 03:58 UTC, FrediKats commented on Source/Kysect.Fluda.Test/CodeGeneration/ClassDeclarationGetterTest.cs
> +            .WriteTo.File("logs.txt")
Стоит писать не в файл, а в дебаг аутпут, чтобы логи привязывались к тестам и отображались в Test explorer'е.

2022-09-27 03:58 UTC, FrediKats commented on Source/Kysect.Fluda.Samples/Program.cs
> +        const string path = @"E:\FludaGenerated";
Сюда тоже, я думаю, стоит сразу докинуть `Log.Logger = new LoggerConfiguration()`. Кажется, что удобно будет делать логи сразу в файл и консоль.

2022-09-27 13:58 UTC, FrediKats approved these changes

2022-09-27 15:00 UTC, merged