Properties parser
kysect/Fluda pull request #135
Opened 2022-09-28 12:59 UTC by Walter-Rabbit

Closed #129 

Достаточно ли распарсить только свойства и не парсить поля в классе?
И второй вопрос, как лучше хранить тип данных в модельке? Через Type или можно string'ом?

2022-09-30 06:33 UTC, FrediKats reviewed
Я не уверен, что хранить строкой - это хорошая идея. Мы, скорее всего, будем поддерживать возможность кастомные типы конфигурировать. И лучше, чтобы они по типу более явно сравнивались, чем по названию.

2022-09-30 06:33 UTC, FrediKats commented on Source/Kysect.Fluda.CodeGeneration/CodeFirst/ValueObjects/CsField.cs
> +}
А почему без конструктора и с сеттерами?)

2022-09-30 06:34 UTC, FrediKats commented
Т.е. у нас сейчас будет мапинг "тип шарпа" => "скл тип", а потом появится возомжность из-вне добавить новый мапинг, какого-то кастомного пользовательского типа в скл тип. И если хранить названия, то как бы коллизии не словить на User или другом типе, который у всех называется также.

2022-10-02 10:04 UTC, Walter-Rabbit commented on Source/Kysect.Fluda.CodeGeneration/CodeFirst/CodeParser/CsTypeParser.cs
> +            not null when csType == typeof(string) => SqlDbType.Char,
Аналогов стрингам в sql много: Char, Text, VarChar, NVarChar, NChar, NText. Можно завести ишую на придумывание того, как конфигурировать стриги.

2022-10-02 10:04 UTC, Walter-Rabbit commented on Source/Kysect.Fluda.CodeGeneration/CodeFirst/CodeParser/CsTypeParser.cs
> +        return csType switch
Можно добавить ишую, чтобы добавить оставшиеся SQL типы. Например Byte Array

2022-10-02 10:06 UTC, Walter-Rabbit commented
Использований у этих конвертеров пока нет, я так понимаю в следующей ишуе, уже буду использовать.

2022-10-02 18:14 UTC, FrediKats requested changes
Предлагаю сразу взять семантик модель, чтобы из неё типы получать, а не мапить строки.

2022-10-02 18:14 UTC, FrediKats commented on Source/Kysect.Fluda.CodeGeneration/CodeFirst/CodeParser/ClassPropertiesParser.cs
> +        Type csType = csTypeParser.GetCSharpTypeFromString(type);
А почему бы не заюзать семантик модель для того, чтобы сразу правильно типы развернуть?

https://stackoverflow.com/questions/33421794/can-we-get-system-type-from-microsoft-codeanalysis-csharp-syntax-typesyntax

2022-10-02 18:14 UTC, FrediKats commented on Source/Kysect.Fluda.CodeGeneration/CodeFirst/CodeParser/CsTypeParser.cs
> +            not null when csType == typeof(string) => SqlDbType.Char,
Но разве Char - это не Char из C#? А так да, можно.

2022-10-02 18:24 UTC, Walter-Rabbit commented on Source/Kysect.Fluda.CodeGeneration/CodeFirst/CodeParser/CsTypeParser.cs
> +            not null when csType == typeof(string) => SqlDbType.Char,
Вроде как нет
![image](https://user-images.githubusercontent.com/60439555/193469854-0c2753b0-3eec-414c-903d-344b0f1e1910.png)
https://learn.microsoft.com/ru-ru/dotnet/api/system.data.sqldbtype?view=net-6.0

2022-10-02 18:34 UTC, Walter-Rabbit commented on Source/Kysect.Fluda.CodeGeneration/CodeFirst/CodeParser/ClassPropertiesParser.cs
> +        Type csType = csTypeParser.GetCSharpTypeFromString(type);
Думал про семантик модель и на этом даже топике в stackoverflow был, но подумал, что это будет излишним как-то. 
Просто чтобы создать симантик модель, нужно ведь root ноду иметь. А мы в этом методе только ClassDeclaration передали. В итоге, как мне показалась, получается странная иерархия, где сервис ClassDeclarationGetter вызывает метод, который парсит свойства и передаёт в этот метод Root ноду. Ну или симантическую модель, которую получил ранее.
И я не уверен, что всё будет работать правильно, когда в одном файле будет несколько классов.

Я могу на днях сделать решение с семантической моделью, потом закину сюда и глянем, как это будет выглядеть. Мб норм.

2022-10-03 06:05 UTC, Walter-Rabbit commented on Source/Kysect.Fluda.CodeGeneration/CodeFirst/CodeParser/ClassPropertiesParser.cs
> +        Type csType = csTypeParser.GetCSharpTypeFromString(type);
А ну вроде нормально работает, если просто ноду с декларацией класса запихнуть. Но надо бы проверить на всех типах потом, чтобы убедиться, что все поддерживаемые типы нормально парсятся.

2022-10-03 10:52 UTC, FrediKats requested changes

2022-10-03 10:52 UTC, FrediKats commented on Source/Kysect.Fluda.CodeGeneration/CodeFirst/CodeParser/ClassPropertiesParser.cs
> +        SemanticModel model = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
Давай в метод вынесем создания семантик модели, а то выглядит очень специфично. Предлагаю выделить сущность, которую мы будет создавать до вызова этого мтеода и кидать туда сразу все синтакс три, чтобы один раз создавать семантик модель. И из неё будет один метод торчать наружу - получение тип. по TypeSyntax,

2022-10-03 10:52 UTC, FrediKats commented on Source/Kysect.Fluda.CodeGeneration/CodeFirst/CodeParser/ClassPropertiesParser.cs
> +    }
Очень подозрительно выглядит)

2022-10-03 10:55 UTC, Walter-Rabbit commented on Source/Kysect.Fluda.CodeGeneration/CodeFirst/CodeParser/ClassPropertiesParser.cs
> +    }
Семантическая модель возвращает почему-то названия типов в виде System_Int32. Чтобы Type.GetType() смог тип вернуть, нужно нижние подчёркивания заменить на точки.

2022-10-03 10:59 UTC, FrediKats commented on Source/Kysect.Fluda.CodeGeneration/CodeFirst/CodeParser/ClassPropertiesParser.cs
> +    }
А если там будут "_"? o_O А оно само не умеет в разруливание этого дела, да?

2022-10-03 11:01 UTC, Walter-Rabbit commented on Source/Kysect.Fluda.CodeGeneration/CodeFirst/CodeParser/ClassPropertiesParser.cs
> +    }
Бан на snake_case получается)

Ну я попробую поискать решение какое-нибудь

2022-10-03 11:54 UTC, Walter-Rabbit commented on Source/Kysect.Fluda.CodeGeneration/CodeFirst/CodeParser/ClassPropertiesParser.cs
> +    }
Моя реализация щас работает только с системными типами. Там используется enum SpecialType, в котором лежат все системные типы. Ну и так как поле в enum не может содержать точку в названии, то все поля тут названы через нижнее подчёркивание. В целом, я думаю тут ничего страшного, так как у системных типов в названии нижнего подчёркивания нет. А если нужно будет сделать поддержку собственных типов, то нужно будет делать ещё одну реализацию парсера в отдельной ишуе.

2022-10-03 15:53 UTC, merged